MAX_ASCII_NUM: int = 127
DATA_INFO_LEN: int = 4
DATA_FORMAT: str = '{0:06b}'
DATA_INFO_BINARY_FORMAT: str = '{0:012b}'
DOT: str = "."
WHAT_TO_DO: str = "Que souhaitez-vous faire ?"
MANAGEMENT: str = "management"
SUPPORT: str = "support"
SALES: str = "sales"
ROLES_LIST: list[str] = [MANAGEMENT, SUPPORT, SALES]